env: "dev"

http_server:
  address: "3000"

database:
  driver: "postgres"
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: "fanligapass"
  database: "fanligafc"
  url: "postgres://postgres:fanligapass@localhost:5432/fanligafc?sslmode=disable"

access_token:
  public_key: "sample_public_key"
  private_key: "sample_private_key"
  encryption_key: "sample_key"
