name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ec2-golang
          chmod 600 ~/.ssh/ec2-golang
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Build Go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o golang-app ./cmd/main.go

      - name: Copy binary to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/ec2-golang" \
          golang-app \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/golang-app/

      - name: Restart app on EC2
        run: |
          ssh -i ~/.ssh/ec2-golang \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo systemctl restart golang-app
          EOF

